project:
  type: website
  output-dir: docs
  
website:
  title: "Profile"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Project.qmd
        text: Project
      - href: Recreational.qmd
        text: Recreational
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

